# Generated by Django 4.2.5 on 2023-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='valor_custo',
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
