# Generated by Django 4.2.5 on 2023-09-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_rename_valor_produto_valor_custo_produto_valor_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriovendas',
            name='vendas',
        ),
        migrations.AddField(
            model_name='venda',
            name='relatorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='sistema.relatoriovendas'),
            preserve_default=False,
        ),
    ]
