# Generated by Django 4.2.5 on 2023-09-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_relatoriovendas_vendas_venda_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='relatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='sistema.relatoriovendas'),
        ),
    ]
