# Generated by Django 4.2.5 on 2023-09-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_relatoriovendas_valorfinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriocaixa',
            name='valorCartao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartao', to='sistema.venda')),
            ],
        ),
    ]
