# Generated by Django 4.2.3 on 2024-10-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_relatoriocaixa_valorcartao_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_minima_para_pedido',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
