# Generated by Django 4.2.3 on 2024-10-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_cliente_venda_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
