# Generated by Django 4.2.3 on 2024-10-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
