# Generated by Django 4.2.3 on 2024-10-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='inscricao_estadual',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
