# Generated by Django 4.2.3 on 2024-10-12 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_alter_fornecedor_inscricao_estadual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotaDeMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='sistema.fornecedor')),
                ('produtos', models.ManyToManyField(through='sistema.ItensNota', to='sistema.produto')),
            ],
        ),
        migrations.AddField(
            model_name='itensnota',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sistema.notademercadoria'),
        ),
        migrations.AddField(
            model_name='itensnota',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_da_nota', to='sistema.produto'),
        ),
    ]
