# Generated by Django 4.2.3 on 2024-10-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_itensnota_notademercadoria_itensnota_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notademercadoria',
            name='numero_nota',
            field=models.CharField(max_length=50),
        ),
    ]
